In [1]:
import numpy as np

# Q1

In [54]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
a.reshape(3,3)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Q2

In [55]:
a = np.arange(10)
print(a)

def negative(a):
    for i in a:
        if i%2 != 0:
            a[i] = -1
negative(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [56]:
a = np.arange(10)
a[a%2 != 0] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Q3     

In [57]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

def greater(x,y):
    gre = []
    for i in range(10):
        if x[i] > y[i]:
            a = i
            gre.append(a)
    print(gre)
def equal(x,y):

    equ = []
    for i in range(10):
        if x[i] == y[i]:
            a = i
            equ.append(a)
    print(equ)
    
greater(x,y)
equal(x,y)

[1, 2, 4, 5, 6, 7, 8, 9]
[0]


In [66]:
xGy = np.nonzero(x>y)
xEy = np.nonzero(x==y)
print(xGy)
print(xEy)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


# Q4

In [59]:
a= np.arange(100).reshape(5,-1)
print(a)
a[:,:4]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

# Additional questions

In [60]:
a = np.random.randint(30,41 ,size=(10))
print(a)

[39 39 30 30 35 37 33 37 32 38]


In [68]:
a= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
b =np.array ([[7, 8, 10] ,[4, 5, 6], [1, 2, 3]])
print("A: \n", a)
print("B: \n",b)
c = a + b
e = a - b
print("\nA + B = \n", c)
print("\nA - B = \n", e)
print("\nSum of all elements of Matrix A\n", a.sum())
print("\nSum of each column of Matrix B\n", b.sum(axis = 0))
print("\nSum of each row of Matrix C\n",c.sum(axis = 1))
d = np.dot(a,b)
print("\nProduct of two matrices A and B\n", d)
c.sort(axis = 0)
e = c
print("\nTranspose the Matrix E\n",e.T)

A: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
B: 
 [[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]

A + B = 
 [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

A - B = 
 [[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

Sum of all elements of Matrix A
 46

Sum of each column of Matrix B
 [12 15 19]

Sum of each row of Matrix C
 [31 30 31]

Product of two matrices A and B
 [[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

Transpose the Matrix E
 [[ 8  8  8]
 [10 10 10]
 [12 13 13]]
